name: "Push Release to AWS CC"
description: "Push a tagged release to AWS CC repo as a single commit"
inputs:
  repository_name:
    description: "Github repository name"
    default: ${{ github.event.repository.name }}
  tag_name:
    description: "Github tag name"
    default: ${{ github.event.release.tag_name }}
  tarball_url:
    description: "Release tarball URL"
    default: ${{ github.event.release.tarball_url }}
  aws_repo_url:
    description: "AWS CC repo URL (HTTPS URL; do not include https:// prefix)"
    required: true
  aws_cc_username:
    description: "AWS CC HTTPS username"
    required: true
  aws_cc_password:
    description: "AWS CC HTTPS password"
    required: true
  aws_cc_branchname:
    description: "AWS CC branch name"
    required: true
  github_token:
    description: "Github access token"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
